### PR TITLE
Singly Linked List

### PR DESCRIPTION
**Pull request by CodesOfAnurag**
Singly Linked List

### CODE REVIEW

**Comment by VIPverma01** [comment]
Well-done but please follow the guidelines mentioned in README and first of all make a request in issue so that I can assign you the issue.

**Comment by CodesOfAnurag** [comment]
Please checkout the pull request #4

**Comment by CodesOfAnurag** [comment]
Singly Linked List using c

**Comment by VIPverma01** [comment]
I have checked your program, nice work @CodesOfAnurag. But please follow the README guidelines and star the Repository first and change your folder name from Singly Linked List to Singly Linked List(Your Username).

**Comment by CodesOfAnurag** [comment]
Oh sorry about that

**Comment by CodesOfAnurag** [comment]
Made the required changes, let me know the needful

**Comment by CodesOfAnurag** [comment]
Made the changes as mentioned by you @VIPverma01

**Pull request merged**
